apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq "Headless" .Values.service.type }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8090
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.topology }}
  topologyKeys:
    {{- toYaml .Values.service.topology | nindent 4 }}
  {{- else if .Values.global.service.topology }}
  topologyKeys:
    {{- toYaml .Values.global.service.topology | nindent 4 }}
  {{- end }}
