apiVersion: v2
type: application
name: tracker
description: A Helm chart for running the deps.cloud tracker process
icon: https://deps.cloud/favicons/logo-small-rounded.png
home: https://deps.cloud
sources:
  - https://github.com/depscloud/depscloud
  - https://github.com/depscloud/deploy
maintainers:
  - name: Mya Pitzeruse
    email: mjpitz@deps.cloud
    url: https://mjpitz.com
version: 0.3.2
appVersion: 0.3.2
