---
---
# Source: depscloud/charts/extractor/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: depscloud-extractor
  labels:
    helm.sh/chart: extractor-0.1.12
    app.kubernetes.io/name: extractor
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.19"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: extractor
    
automountServiceAccountToken: false
---
# Source: depscloud/charts/gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: depscloud-gateway
  labels:
    helm.sh/chart: gateway-0.1.12
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: gateway
    
automountServiceAccountToken: false
---
# Source: depscloud/charts/indexer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: depscloud-indexer
  labels:
    helm.sh/chart: indexer-0.1.13
    app.kubernetes.io/name: indexer
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: indexer
    
automountServiceAccountToken: false
---
# Source: depscloud/charts/tracker/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: depscloud-tracker
  labels:
    helm.sh/chart: tracker-0.1.17
    app.kubernetes.io/name: tracker
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.16"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: tracker
    
automountServiceAccountToken: false
---
# Source: depscloud/charts/extractor/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: depscloud-extractor
  labels:
    helm.sh/chart: extractor-0.1.12
    app.kubernetes.io/name: extractor
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.19"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: extractor
    
spec:
  clusterIP: None
  ports:
    - port: 8090
      targetPort: grpc
      protocol: TCP
      name: grpclb
  selector:
    app.kubernetes.io/name: extractor
    app.kubernetes.io/instance: depscloud
---
# Source: depscloud/charts/gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: depscloud-gateway
  labels:
    helm.sh/chart: gateway-0.1.12
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: gateway
    
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: depscloud
---
# Source: depscloud/charts/tracker/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: depscloud-tracker
  labels:
    helm.sh/chart: tracker-0.1.17
    app.kubernetes.io/name: tracker
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.16"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: tracker
    
spec:
  clusterIP: None
  ports:
    - port: 8090
      targetPort: grpc
      protocol: TCP
      name: grpclb
  selector:
    app.kubernetes.io/name: tracker
    app.kubernetes.io/instance: depscloud
---
# Source: depscloud/charts/extractor/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depscloud-extractor
  labels:
    helm.sh/chart: extractor-0.1.12
    app.kubernetes.io/name: extractor
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.19"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: extractor
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: extractor
      app.kubernetes.io/instance: depscloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: extractor
        app.kubernetes.io/instance: depscloud
    spec:
      serviceAccountName: depscloud-extractor
      securityContext:
        {}
      volumes:
      containers:
        - name: extractor
          securityContext:
            {}
          image: "depscloud/extractor:0.2.19"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          args:
            - --port=8090
          ports:
            - name: grpc
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:8090"]
            initialDelaySeconds: 5
          readinessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:8090"]
            initialDelaySeconds: 5
          resources:
            {}
---
# Source: depscloud/charts/gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depscloud-gateway
  labels:
    helm.sh/chart: gateway-0.1.12
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: gateway
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/instance: depscloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/instance: depscloud
    spec:
      serviceAccountName: depscloud-gateway
      securityContext:
        {}
      volumes:
      containers:
        - name: gateway
          securityContext:
            {}
          image: "depscloud/gateway:0.2.13"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          args:
            - --extractor-address=dns:///depscloud-extractor:8090
            - --port=8080
            - --tracker-address=dns:///depscloud-tracker:8090
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1alpha/sources # todo: replace with healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /v1alpha/sources # todo: replace with healthz
              port: 8080
          resources:
            {}
---
# Source: depscloud/charts/tracker/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depscloud-tracker
  labels:
    helm.sh/chart: tracker-0.1.17
    app.kubernetes.io/name: tracker
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.16"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: tracker
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tracker
      app.kubernetes.io/instance: depscloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracker
        app.kubernetes.io/instance: depscloud
    spec:
      serviceAccountName: depscloud-tracker
      securityContext:
        {}
      volumes:
      containers:
        - name: tracker
          securityContext:
            {}
          image: "depscloud/tracker:0.2.16"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: depscloud-tracker
          volumeMounts:
          args:
            - --port=8090
            - --storage-driver=$(STORAGE_DRIVER)
            - --storage-address=$(STORAGE_ADDRESS)
            - --storage-readonly-address=$(STORAGE_READ_ONLY_ADDRESS)
          ports:
            - name: grpc
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:8090"]
            initialDelaySeconds: 5
          readinessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:8090"]
            initialDelaySeconds: 5
          resources:
            {}
---
# Source: depscloud/charts/indexer/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: depscloud-indexer
  labels:
    helm.sh/chart: indexer-0.1.13
    app.kubernetes.io/name: indexer
    app.kubernetes.io/instance: depscloud
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: deps.cloud
    app.kubernetes.io/component: indexer
    
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: depscloud-indexer
      securityContext:
        {}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          secret:
            secretName:  depscloud-indexer
      containers:
        - name: indexer
          securityContext:
            {}
          image: "depscloud/indexer:0.2.13"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/indexer
              name: config
            - mountPath: /tmp
              name: tmp
              readOnly: false
          args:
            - --extractor-address=dns:///depscloud-extractor:8090
            - --config=/etc/indexer/config.yaml
            - --ssh-keypath=
            - --ssh-user=
            - --tracker-address=dns:///depscloud-tracker:8090
            - --workers=5
          resources:
            {}
