apiVersion: v2
type: application
name: extractor
description: A Helm chart for running the deps.cloud extractor process
icon: https://deps.cloud/favicons/logo-small-rounded.png
home: https://deps.cloud
sources:
  - https://github.com/depscloud/depscloud
  - https://github.com/depscloud/deploy
maintainers:
  - name: Mya Pitzeruse
    email: mjpitz@deps.cloud
    url: https://mjpitz.com
version: 0.2.32
appVersion: 0.2.32
