apiVersion: v1
kind: Service
metadata:
  name: {{ include "extractor.fullname" . }}
  labels:
    {{- include "extractor.labels" . | nindent 4 }}
spec:
  {{- if eq "Headless" .Values.service.type }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8090
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "extractor.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.topology }}
  topologyKeys:
    {{- toYaml .Values.service.topology | nindent 4 }}
  {{- else if .Values.global.service.topology }}
  topologyKeys:
    {{- toYaml .Values.global.service.topology | nindent 4 }}
  {{- end }}
