global:
  # labels applied to all subcharts
  labels: {}

mysql:
  enabled: false

postgres:
  enabled: false

extractor:
  enabled: true

gateway:
  enabled: true
  extractor:
    address: ""
  tracker:
    address: ""

indexer:
  enabled: true
  schedule: ""
  extractor:
    address: ""
  tracker:
    address: ""

tracker:
  enabled: true
