# Configuration shared across all charts. Each chart supports per service and
# global configuration, making it easy to configure and deploy the system.
global:
  # -- Common labels added to all resources.
  labels: {}
  service:
    # -- Configure the routing topology. Requires ServiceTopology feature gate and ClusterIP.
    topology: []
    #  - "kubernetes.io/hostname"
    #  - "topology.kubernetes.io/zone"
    #  - "topology.kubernetes.io/region"
  # Common metrics configuration.
  metrics:
    serviceMonitor:
      # -- Create a Prometheus ServiceMonitor.
      enabled: false
      # -- Configure the scrape interval used by the monitor.
      interval: 10s

mysql:
  # -- Deploy a copy of MySQL alongside deps.cloud. Useful for quick testing.
  # Not recommended for production.
  enabled: false

postgres:
  # -- Deploy a copy of PostgreSQL alongside deps.cloud. Useful for quick testing.
  # Not recommended for production.
  enabled: false

extractor:
  # -- Deploy the extractor process.
  enabled: true

gateway:
  # -- Deploy the gateway process.
  enabled: true
  extractor:
    # -- Configures the connection string for the extractor.
    address: ""
  tracker:
    # -- Configures the connection string for the tracker.
    address: ""

indexer:
  # -- Deploy the indexer process.
  enabled: true
  # -- When `""`, the indexer will run as a one-time job.
  # Otherwise, it will run on the specified cron schedule.
  schedule: ""
  extractor:
    # -- Configures the connection string for the extractor.
    address: ""
  tracker:
    # -- Configures the connection string for the tracker.
    address: ""

tracker:
  # -- Deploy and configure the tracker process.
  enabled: true

ingress:
  # -- Expose depscloud using an ingress controller. Must support gRPC.
  enabled: false
  # -- Specify any ingress-controller specific annotations. The CLI
  # requires gRPC to work properly. Be sure your networking stack
  # supports it. Should you need help for your provider, don't hesitate
  # to reach out.
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  # nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  # nginx.ingress.kubernetes.io/enable-cors: "true"
  # -- Configures host / path pairings
  hosts: []
  # - host: depscloud.example.local
  #   paths:
  #     - /
  # -- Configures TLS for the ingress route on some domain.
  tls: []
  # - secretName: depscloud-tls
  #   hosts:
  #     - depscloud.example.local
  backend:
    # -- The name of the service to target. Defaults to "{{ .Release.Name }}-gateway".
    serviceName: ""
    # -- The port to target.
    servicePort: "http"
