# Configuration shared across all charts. Each chart supports per service and
# global configuration, making it easy to configure and deploy the system.
global:
  # Common labels added to all resources.
  labels: {}

  # Common service configuration. Used to configure routing topology.
  service: {}
  #  topology:
  #    - "kubernetes.io/hostname"
  #    - "topology.kubernetes.io/zone"
  #    - "topology.kubernetes.io/region"

  # Common metrics configuration.
  metrics:
    serviceMonitor:
      enabled: false
      interval: 10s

# Deploy a copy of MySQL alongside deps.cloud. Useful for quick testing.
# Not recommended for production.
mysql:
  enabled: false

# Deploy a copy of PostgreSQL alongside deps.cloud. Useful for quick testing.
# Not recommended for production.
postgres:
  enabled: false

# Deploy and configure the extractor process.
extractor:
  enabled: true

# Deploy and configure the gateway process.
gateway:
  enabled: true
  extractor:
    address: ""
  tracker:
    address: ""

# Deploy and configure the indexer process.
indexer:
  enabled: true
  schedule: ""
  extractor:
    address: ""
  tracker:
    address: ""

# Deploy and configure the tracker process.
tracker:
  enabled: true
