---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: depscloud-sqlite
spec:
  releaseName: depscloud-sqlite
  chart:
    repository: https://depscloud.github.io/deploy/charts
    name: depscloud
  values:
    extractor:
      enabled: true

    gateway:
      enabled: true

    indexer:
      enabled: true
      schedule: "@daily"
      config:
        accounts:
          - github:
              clone:
                strategy: HTTP
              organizations:
                - depscloud

    tracker:
      enabled: true
      storage:
        driver: sqlite
        address: file::memory:?cache=shared
        readOnlyAddress:
