name: charts

on:
  pull_request:
    paths:
      - ".github/workflows/charts.yaml"
      - "charts/**"
  push:
    paths:
      - ".github/workflows/branch.yaml"
      - "charts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm version
          make public/charts public/k8s

