name: monitoring

on:
  pull_request:
    paths:
      - "monitoring/**"
  push:
    paths:
      - "monitoring/**"

jobs:
  jsonnet:
    runs-on: ubuntu-latest
    container:
      image: quay.io/coreos/jsonnet-ci:release-0.38
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Make
        run: |
          cd monitoring
          jb install
          make
